// AUTO-GENERATED by scripts/generate-workflow-data.js — 2026-07-14
// 87 workflows: 31 active, 31 inactive, 25 archived
const WORKFLOWS = [
 {
  "name": "AI LinkedIn Image Generator",
  "id": "IZ1LdYCLlJZM1Zyd",
  "status": "active",
  "cat": "content",
  "desc": "Takes a brief or topic via form and generates a LinkedIn-ready image with AI.",
  "inputs": "Brief / topic (form)",
  "outputs": "Generated image",
  "trigger": "n8n Form",
  "cost": "$0.05",
  "costUnit": "per image",
  "costSource": "est"
 },
 {
  "name": "April 2026: UPWORK JOB EXTRACTION v3 (new actor)",
  "id": "m017oOt8S4VGeM6V",
  "status": "active",
  "cat": "upwork",
  "desc": "Scrapes fresh Upwork jobs per consultant every ~2.5h, dedupes against history, creates a ClickUp task for each new matching job.",
  "inputs": "ClickUp trigger + per-consultant config",
  "outputs": "New ClickUp tasks (one per job)",
  "trigger": "ClickUp webhook",
  "cost": "$0.05",
  "costUnit": "per run",
  "costSource": "est"
 },
 {
  "name": "Content Repurposer — Caption & Brief Generator",
  "id": "RKpQuQL6rIfe4C3i",
  "status": "active",
  "cat": "content",
  "desc": "Content Repurposer: turns source content into platform-ready captions and creative briefs.",
  "inputs": "Source content",
  "outputs": "Captions + briefs",
  "trigger": "Webhook",
  "cost": "$0.03",
  "costUnit": "per run",
  "costSource": "measured"
 },
 {
  "name": "GTM LinkedIn All Combined (Optimised)",
  "id": "fw9BkUjzLm369i8H",
  "status": "active",
  "cat": "linkedin",
  "desc": "Master orchestrator for all LinkedIn audit + outreach work. Routes leads to the right audit, generates 6 types of personalised DMs, handles approval and email delivery, logs everything to Sheets.",
  "inputs": "Lead (LinkedIn URL) via 5 webhooks",
  "outputs": "Audit doc + DM set + client email + Sheets log",
  "trigger": "Webhook ×5",
  "cost": "$0.11",
  "costUnit": "per run",
  "costSource": "measured"
 },
 {
  "name": "GTM Scan — Lead Router + Audit Generator",
  "id": "LHGG3RpmWevtBAnG",
  "status": "active",
  "cat": "linkedin",
  "desc": "GTM Scan: routes inbound leads and auto-generates the right audit for each one — front door of the GTM funnel.",
  "inputs": "Inbound lead",
  "outputs": "Routed lead + generated audit",
  "trigger": "Webhook",
  "cost": "$0.49",
  "costUnit": "per run",
  "costSource": "measured"
 },
 {
  "name": "Instagram Reel Intelligence Pipeline",
  "id": "doiwqpa0ppPREtbA",
  "status": "active",
  "cat": "content",
  "desc": "Scrapes an IG profile/reels via Apify, Claude analyses themes, hooks and engagement patterns, produces reel scripts + an intelligence report. Recently retuned for the client's audience.",
  "inputs": "IG profile or reel URL",
  "outputs": "Intelligence report + reel scripts in Sheets",
  "trigger": "Webhook + Manual",
  "cost": "$0.24",
  "costUnit": "per run",
  "costSource": "measured"
 },
 {
  "name": "Jarvis — Failure Watchdog",
  "id": "RnZdISAt9xXBaoi5",
  "status": "active",
  "cat": "internal",
  "desc": "Failure Watchdog: catches ANY workflow failure fleet-wide and emails an alert with an Auto-Fix button. Disabled 4 Jul 2026.",
  "inputs": "Any n8n execution failure",
  "outputs": "Alert email",
  "trigger": "Error trigger",
  "jarvis": true
 },
 {
  "name": "LinkedIn ICP + Complete Strategy Doc + Themes + Ideas + Post Generator",
  "id": "KG0gnHRoJ8awSEJH",
  "status": "active",
  "cat": "linkedin",
  "desc": "Full content strategy: intake form → 5 AI agents (Audit, Revamp, TOV, Strategy, Calendar) → approval-gated Themes → Ideas → Posts → Captions. Final deliverable is a Google Doc.",
  "inputs": "Client intake form + phase approvals",
  "outputs": "Strategy Google Doc + posts in Sheets",
  "trigger": "Form + 4 webhooks",
  "cost": "$0.14",
  "costUnit": "per client",
  "costSource": "measured"
 },
 {
  "name": "LinkedIn Positioning Project Plan",
  "id": "m9b9AeqpF18e15AX",
  "status": "active",
  "cat": "linkedin",
  "desc": "LinkedIn URL + call transcript → Apify scrape → Claude writes a 5-section positioning project plan, delivered as a Google Doc.",
  "inputs": "LinkedIn URL + transcript",
  "outputs": "Positioning plan Google Doc",
  "trigger": "Webhook",
  "cost": "$0.08",
  "costUnit": "per run",
  "costSource": "measured"
 },
 {
  "name": "LinkedIn Sales Navigator Lead Scraper",
  "id": "i1GI1n67WK6Rg5b3",
  "status": "active",
  "cat": "linkedin",
  "desc": "Takes a Sales Navigator search URL, scrapes all leads via Apify (async with retry loop), writes name / company / title / URL / location to a Google Sheet.",
  "inputs": "Sales Navigator search URL",
  "outputs": "Lead list in Google Sheets",
  "trigger": "Webhook",
  "cost": "$2.03",
  "costUnit": "per search",
  "costSource": "measured"
 },
 {
  "name": "LinkedIn Viral Post Monitor Gmail",
  "id": "O9fEXbJlqIS584JC",
  "status": "active",
  "cat": "content",
  "desc": "Scrapes LinkedIn posts, Claude Haiku scores each for virality, filters the winners and emails a digest — used for content inspiration and competitor monitoring.",
  "inputs": "Profile / search criteria",
  "outputs": "Curated viral-post digest email",
  "trigger": "Webhook",
  "cost": "$0.12",
  "costUnit": "per run",
  "costSource": "measured"
 },
 {
  "name": "March 2026: PROPOSAL GENERATOR FINAL",
  "id": "YFnSv6prCiqjlM7Z",
  "status": "active",
  "cat": "upwork",
  "desc": "Generates an Upwork proposal in a specific consultant's voice (6 consultant profiles), formats it as a doc, uploads to Drive, posts the link back as a ClickUp comment.",
  "inputs": "Job details + consultant identity",
  "outputs": "Proposal doc in Drive + ClickUp comment",
  "trigger": "Webhook",
  "cost": "$0.03",
  "costUnit": "per proposal",
  "costSource": "measured"
 },
 {
  "name": "March 2026: Upwork Account Status - Complete Monitor Updated",
  "id": "0wyiOLJUEgff2N3r",
  "status": "active",
  "cat": "upwork",
  "desc": "Monitors Upwork account status for consultants and alerts on changes.",
  "inputs": "Account status checks",
  "outputs": "Status alerts",
  "trigger": "Webhook",
  "cost": "$0.01",
  "costUnit": "per run",
  "costSource": "est"
 },
 {
  "name": "Replicate Image Generator from Google Sheets",
  "id": "GBSecXH94ZCtCJvm",
  "status": "active",
  "cat": "content",
  "desc": "Reads image prompts from a Google Sheet, generates via Replicate, uploads to Drive and writes the link back to the sheet. Batch with async polling.",
  "inputs": "Prompts in Google Sheet",
  "outputs": "Images in Drive + links in sheet",
  "trigger": "Manual",
  "cost": "$0.02",
  "costUnit": "per image",
  "costSource": "est"
 },
 {
  "name": "SEO Pipeline — Workflow E: Keyword Discovery",
  "id": "FqhhMcXdICmQdQqs",
  "status": "active",
  "cat": "seo",
  "desc": "Discovers and queues new keywords on a schedule for the main SEO pipeline to process.",
  "inputs": "Schedule",
  "outputs": "Queued keywords in Sheets",
  "trigger": "Schedule",
  "cost": "$0.02",
  "costUnit": "per run",
  "costSource": "measured"
 },
 {
  "name": "SEO Pipeline Final All",
  "id": "gkNsOpDjnRF1SNGe",
  "status": "active",
  "cat": "seo",
  "desc": "End-to-end SEO: keyword research (DataForSEO) → competitor scrape (Jina) → Claude brief (approval) → Claude article (approval) → AI image → Webflow draft. Plus weekly Search Console digest.",
  "inputs": "Keyword (webhook) or Monday schedule",
  "outputs": "Published Webflow article + GSC digest email",
  "trigger": "Webhook + Schedule",
  "cost": "$0.18",
  "costUnit": "per run",
  "costSource": "measured"
 },
 {
  "name": "Short TOV from LinkedIn Profile",
  "id": "XnBHKk6FMgZc920h",
  "status": "active",
  "cat": "linkedin",
  "desc": "LinkedIn URL → Apify scrape → Claude extracts a short tone-of-voice guide, used as input to content, proposal and audit workflows.",
  "inputs": "LinkedIn profile URL",
  "outputs": "Tone-of-voice guide",
  "trigger": "Webhook",
  "cost": "$0.06",
  "costUnit": "per run",
  "costSource": "est"
 },
 {
  "name": "ShortLinkedinStrategyPlaybook",
  "id": "UbXB5lOIA42CMSsq",
  "status": "active",
  "cat": "linkedin",
  "desc": "LinkedIn profile URL → Apify scrape → Claude writes a short, structured LinkedIn strategy playbook, delivered as a Google Doc.",
  "inputs": "LinkedIn profile URL",
  "outputs": "Strategy playbook Google Doc",
  "trigger": "Webhook",
  "cost": "$0.10",
  "costUnit": "per run",
  "costSource": "est"
 },
 {
  "name": "Soch Deal Desk — Transcript to LOI/Proposal/SOW",
  "id": "wrgytxLjMqVJUVou",
  "status": "active",
  "cat": "leads",
  "desc": "Deal Desk: takes a sales-call transcript → Claude analyses the deal → generates LOI / Proposal / SOW documents + a branded slide deck, delivered automatically.",
  "inputs": "Sales call transcript",
  "outputs": "LOI / Proposal / SOW docs + slide deck",
  "trigger": "Webhook",
  "cost": "$0.42",
  "costUnit": "per deal",
  "costSource": "measured"
 },
 {
  "name": "Soch Ops Score - Lead Report",
  "id": "5gIDlIS9vwKASs0O",
  "status": "active",
  "cat": "leads",
  "desc": "When a lead submits the Webflow form, scores their business-ops readiness, generates a personalised report and emails it to them automatically.",
  "inputs": "Webflow form submission",
  "outputs": "Scored report emailed to lead",
  "trigger": "Webflow form",
  "cost": "$0.05",
  "costUnit": "per lead",
  "costSource": "measured"
 },
 {
  "name": "SochCatalyst Lead Capture",
  "id": "aqpvBmZJDJG3PUkv",
  "status": "active",
  "cat": "leads",
  "desc": "Receives inbound leads from SochCatalyst and processes + stores the lead data — entry point of the SochCatalyst pipeline.",
  "inputs": "Inbound SochCatalyst lead",
  "outputs": "Processed + stored lead record",
  "trigger": "Webhook",
  "cost": "$0.04",
  "costUnit": "per lead",
  "costSource": "measured"
 },
 {
  "name": "Viral LinkedIn Post Scraper Google Sheet",
  "id": "3LJeJ2tQPTtTwZuh",
  "status": "active",
  "cat": "content",
  "desc": "Takes search criteria or a profile and scrapes LinkedIn for viral posts via Apify, returning a curated list.",
  "inputs": "Search criteria / profile",
  "outputs": "Curated viral post list",
  "trigger": "Webhook + Manual",
  "cost": "$0.15",
  "costUnit": "per run",
  "costSource": "est"
 },
 {
  "name": "X Trending to LinkedIn Posts",
  "id": "pBtmxBG68O2AQf41",
  "status": "active",
  "cat": "content",
  "desc": "Takes trending X (Twitter) topics and has Claude rewrite them as LinkedIn posts.",
  "inputs": "Trending X topics",
  "outputs": "LinkedIn-ready posts",
  "trigger": "Webhook",
  "cost": "$0.03",
  "costUnit": "per run",
  "costSource": "est"
 },
 {
  "name": "YouTube Content Intelligence — Weekly",
  "id": "6z9jHPTSCCZSb48i",
  "status": "active",
  "cat": "content",
  "desc": "Weekly sweep of YouTube content in the niche; Claude analyses trends, themes and top-performing patterns; produces video briefs + a report.",
  "inputs": "Schedule (weekly) or manual",
  "outputs": "Trend report + video briefs",
  "trigger": "Schedule (weekly)",
  "cost": "$0.49",
  "costUnit": "per run",
  "costSource": "measured"
 },
 {
  "name": "Attio → ClickUp: Reverse Sync",
  "id": "EhAwuknOt7OeLGhT",
  "status": "active",
  "cat": "other"
 },
 {
  "name": "ClickUp → Attio: Forward Sync",
  "id": "eoaQ6tdv9xiAmT3o",
  "status": "active",
  "cat": "other"
 },
 {
  "name": "Instantly → ClickUp: Lead Intake",
  "id": "9PhvrsyChlPLwAYe",
  "status": "active",
  "cat": "leads"
 },
 {
  "name": "Reddit Lead-Gen ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬ï¿½ Draft & Review Queue",
  "id": "3Sn9WbpY7kv5Sj0t",
  "status": "active",
  "cat": "leads"
 },
 {
  "name": "Reimbursements - Approval Reminder",
  "id": "v5SbUhVpe3QFAkeN",
  "status": "active",
  "cat": "other"
 },
 {
  "name": "Soch Pre-Call Flow (Riz Nurture)",
  "id": "vVaMKk7aVZfbNmCi",
  "status": "active",
  "cat": "other"
 },
 {
  "name": "Upwork Bidding → Leads Pipeline: Move to Attio",
  "id": "wOrC76HNLFNzwGrU",
  "status": "active",
  "cat": "upwork"
 },
 {
  "name": "Jarvis - Autofix Request",
  "id": "ssDL2ic8pPebIOEb",
  "status": "inactive",
  "cat": "internal",
  "desc": "Queues an autofix request and fires the Autofix Worker. Disabled 4 Jul 2026.",
  "inputs": "Auto-Fix button click",
  "outputs": "Queued fix request",
  "trigger": "Webhook",
  "jarvis": true
 },
 {
  "name": "Jarvis - Autofix Worker",
  "id": "lyS8OFJRBM5Zm4eQ",
  "status": "inactive",
  "cat": "internal",
  "desc": "Autofix Worker: fetches the failed execution, Claude diagnoses + patches the workflow, re-activates, reports. Disabled 4 Jul 2026.",
  "inputs": "Fix request",
  "outputs": "Patched workflow + report",
  "trigger": "Webhook",
  "jarvis": true
 },
 {
  "name": "Jarvis — Autofix Report",
  "id": "75dmfdF1Toeq2hrl",
  "status": "inactive",
  "cat": "internal",
  "desc": "Builds and sends the autofix outcome report email. Disabled 4 Jul 2026.",
  "inputs": "Autofix outcome",
  "outputs": "Fix report email",
  "trigger": "Webhook",
  "jarvis": true
 },
 {
  "name": "Jarvis — Docs & Sheets Utility",
  "id": "g4NiusZAfsevXG7Z",
  "status": "inactive",
  "cat": "internal",
  "desc": "Internal API gateway for Google Sheets/Docs operations, used by the Autofix worker and Discord bot. Disabled 4 Jul 2026.",
  "inputs": "Internal API calls",
  "outputs": "Sheets/Docs operations",
  "trigger": "Webhook",
  "jarvis": true
 },
 {
  "name": "Jarvis — Morning Briefing",
  "id": "OutmMzSAPaK4ZAZT",
  "status": "inactive",
  "cat": "internal",
  "desc": "Daily briefing: pulls unread Gmail, ClickUp tasks due, workflow failures (24h) and Calendar events; Claude composes one email. Disabled 4 Jul 2026.",
  "inputs": "Schedule",
  "outputs": "Briefing email",
  "trigger": "Schedule (daily)",
  "jarvis": true
 },
 {
  "name": "News Digest — Every 6 Hours",
  "id": "kNMnMfXqNIFRkJ0G",
  "status": "inactive",
  "cat": "content",
  "desc": "Every 6 hours: fetches news across 8 topics, Claude summarises, emails a digest.",
  "inputs": "Schedule",
  "outputs": "News digest email",
  "trigger": "Schedule (6h)",
  "cost": "$0.02",
  "costUnit": "per run",
  "costSource": "measured"
 },
 {
  "name": "About Section Audit & Rewrite",
  "id": "9NJniChLiEJdLUwB",
  "status": "inactive",
  "cat": "linkedin"
 },
 {
  "name": "All Clients - Upwork Message Alert â†’ ClickUp Channel",
  "id": "Y2Drfp1vIezN2fXG",
  "status": "inactive",
  "cat": "upwork"
 },
 {
  "name": "Daily RSS News Digest - 5 Topics (8am PKT)",
  "id": "Dq787Vw0XFkAD5ut",
  "status": "inactive",
  "cat": "content"
 },
 {
  "name": "Final Linkedin Short Audit",
  "id": "Nhfc4uJEfFAmNwcL",
  "status": "inactive",
  "cat": "linkedin"
 },
 {
  "name": "ICP Strategy Generator",
  "id": "wrJ2ZE5QkTAwTRWn",
  "status": "inactive",
  "cat": "linkedin"
 },
 {
  "name": "LinkedIn DM Automation — Data Enrichment",
  "id": "Kw18R1HKLBTWhpoM",
  "status": "inactive",
  "cat": "linkedin"
 },
 {
  "name": "LinkedIn Engagement Automation",
  "id": "itCmyMOj9d3EzY0Y",
  "status": "inactive",
  "cat": "linkedin"
 },
 {
  "name": "LinkedIn Job Scraper - Automation Roles",
  "id": "RrdJlbS37wPUfvmk",
  "status": "inactive",
  "cat": "linkedin"
 },
 {
  "name": "LinkedIn Profile Scraper → Sheet Filler",
  "id": "WAvY5NcKErrqOj35",
  "status": "inactive",
  "cat": "linkedin"
 },
 {
  "name": "LinkedIn Profile Stats — Google Sheet",
  "id": "EZLWmpT7Y55Ssuq8",
  "status": "inactive",
  "cat": "linkedin"
 },
 {
  "name": "LinkedIn Profile Stats — Google Sheet  100-200",
  "id": "GFxa6P1VkVVCevdL",
  "status": "inactive",
  "cat": "linkedin"
 },
 {
  "name": "LinkedIn Profile Stats — Google Sheet  201-300",
  "id": "2kCHBIGMgGarSTJG",
  "status": "inactive",
  "cat": "linkedin"
 },
 {
  "name": "LinkedIn Profile Stats — Google Sheet  301-404",
  "id": "h0tvqeI4HKdbFkrs",
  "status": "inactive",
  "cat": "linkedin"
 },
 {
  "name": "My workflow",
  "id": "ryY2ZtVYbk8ZBEGd",
  "status": "inactive",
  "cat": "test"
 },
 {
  "name": "Reddit Lead-Gen — Draft & Review Queue",
  "id": "gBwLt4iUsJF54CEY",
  "status": "inactive",
  "cat": "leads"
 },
 {
  "name": "Reels Trends Watcher (Google Sheets)",
  "id": "vvG3i7HGHSk83ZNg",
  "status": "inactive",
  "cat": "content"
 },
 {
  "name": "Sending Emails to Team Members not on Clickup",
  "id": "aEtC73Q2wGnCnQsG",
  "status": "inactive",
  "cat": "content"
 },
 {
  "name": "SEO Pipeline - A: Content Generation",
  "id": "V1idVqyYCQ0lV8iJ",
  "status": "inactive",
  "cat": "seo"
 },
 {
  "name": "SEO Pipeline - B: Image Generation",
  "id": "G1ZX9tCbWEIvhefY",
  "status": "inactive",
  "cat": "seo"
 },
 {
  "name": "SEO Pipeline - C: Publish & Notify",
  "id": "MNMn76d6zpfYawuL",
  "status": "inactive",
  "cat": "seo"
 },
 {
  "name": "SEO Pipeline - D: GSC Monitoring",
  "id": "z5rnCotdkqFzbINI",
  "status": "inactive",
  "cat": "seo"
 },
 {
  "name": "SEO Pipeline - E: Error Handler",
  "id": "vPg4AqJs3D2IzhlG",
  "status": "inactive",
  "cat": "seo"
 },
 {
  "name": "Soch Post Audit Generator",
  "id": "miCF5FTEEF1mf6Dy",
  "status": "inactive",
  "cat": "linkedin"
 },
 {
  "name": "Sovereign Brand — MVP v0 (Sandwich Proof)",
  "id": "KEPXkNF4rBKi1fpB",
  "status": "inactive",
  "cat": "test"
 },
 {
  "name": "Vollna Jobs Google Sheets",
  "id": "DNoGRdmAJYgyAGAu",
  "status": "inactive",
  "cat": "upwork"
 },
 {
  "name": "About Section Audit & Rewrite",
  "id": "m0K5I3SRLxms9aCJ",
  "status": "archived",
  "cat": "linkedin"
 },
 {
  "name": "ClickUp to Proposals Upwork Auto-Generator V1",
  "id": "8j0O89wSOAsTO6KX",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "ClickUp to Proposals Upwork Auto-Generator V2",
  "id": "aL6TEgLEiXGRDzhA",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "ClickUp to Proposals Upwork Auto-Generator V3",
  "id": "SQauivoeGgUnR8xx",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "ClickUp to Proposals Upwork Auto-Generator V3",
  "id": "g7kbYg9Fvp7YmS94",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "ClickUp to Proposals Upwork Auto-Generator V4",
  "id": "0SzWZJaj0BifAN0X",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "ClickUp to Proposals Upwork Auto-Generator V5",
  "id": "kYGEE1FFmSnwp6uf",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "Clickup Webhook Test",
  "id": "PDiDYzq1LiihTF28",
  "status": "archived",
  "cat": "test"
 },
 {
  "name": "Daily RSS News - Sports, History, Finance, Politics, AI",
  "id": "Qgu40RsVcqz7Rw6C",
  "status": "archived",
  "cat": "content"
 },
 {
  "name": "Final Proposal Writer Final - GPT 5.2 with additional instructions and different filters for new consultants",
  "id": "35k7naCQI2vR3XbB",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "Gmail to Slack: AI-scored Upwork job alerts with OpenRouter",
  "id": "bgV5yIyHijkTVjr5",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "LinkedIn Message + Email",
  "id": "mk2KwUoSAAZF6wHZ",
  "status": "archived",
  "cat": "linkedin"
 },
 {
  "name": "Linkedin Short Audit - Claude Code",
  "id": "2os4IQFV8Zq5tI7j",
  "status": "archived",
  "cat": "linkedin"
 },
 {
  "name": "Proposal Writer Final - GPT 5.2",
  "id": "oTfjYI2bJNtdcjPE",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "Proposal Writer Final - GPT 5.2 copy",
  "id": "rGgnaeVGZhIikqAE",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "Proposal Writer Final - GPT 5.2 with additional instructions",
  "id": "U62mpcz16eu9e8OH",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "Proposal Writer Final - GPT 5.2 with additional instructions and different filters for consultants",
  "id": "bpGSCiI5V3yrmM3w",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "Proposal Writer Final V1 - GPT 4.o",
  "id": "NtSlSHwCpc51IgKz",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "Proposal Writer Final V1 - GPT 5.2",
  "id": "f1LyOSTMXD2kq7O7",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "Upwork Account Status - Complete Monitor",
  "id": "p2bGMgUq2pIPXhER",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "Upwork Account Status - Complete Monitor Updated",
  "id": "9W9q6lIjsMB3sw0x",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "Upwork Job Extracting on Clickup - Consultant",
  "id": "wZMHHaK8gUBEDk6v",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "Upwork Job Extraction - Control Panel",
  "id": "UZbHoVtYGoKCp3th",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "Upwork Job Extraction - Control Panel",
  "id": "x1AKZHWyQT5fc6rk",
  "status": "archived",
  "cat": "upwork"
 },
 {
  "name": "Upwork Logout Reminder - 6 Hour Check",
  "id": "dLnE4fIWI9bKOENL",
  "status": "archived",
  "cat": "upwork"
 }
];
